name: Build WF
on:
  push:
    branches:
      - main

  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
  schedule:
    - cron: "0 2 * * *"   # nightly run at 2 AM UTC

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
        
      - name: Maven Build
        run: mvn install

      - name: Upload Artifact(WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: |
          echo "Build failed. Sending notification email..."
        
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
        
      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle